const { emitterProfilePayloadSchema } = require("./emitterProfiles");

const STARTER_RADAR_PROFILE_COLOR = "#ef4444";

const STARTER_RADAR_PROFILE_DEFINITIONS = [
  {
    key: "long-range-early-warning-radar",
    name: "Long-Range Early Warning Radar",
    profile: {
      type: "sensor",
      emitterLabel: "Long-Range Early Warning Radar",
      force: "enemy",
      icon: "sensor",
      color: STARTER_RADAR_PROFILE_COLOR,
      notes: "Broad-area long-range surveillance radar optimized for wide azimuth coverage and early warning against aircraft and cruise-missile sized targets.",
      rf: { frequencyMHz: 1250, bandwidthKHz: 8000, modulation: "Pulse", waveform: "Volume Search", duplex: "simplex", channelSpacingKHz: 5000 },
      tx: { powerW: 850000, dutyCycle: 0.18, papr: 0, spectralEfficiency: null },
      rx: { sensitivityDbm: -103, noiseFigDb: 4, requiredSnrDb: 13, acrDb: 80, bdrDb: 90 },
      antenna: { type: "phased-array", gainDbi: 33, pattern: "sectoral", polarization: "linear", heightM: 14, cableLossDb: 1.2, systemLossDb: 4 },
      prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
      network: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 120, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
    },
  },
  {
    key: "vhf-early-warning-radar",
    name: "VHF Early Warning Radar",
    profile: {
      type: "sensor",
      emitterLabel: "VHF Early Warning Radar",
      force: "enemy",
      icon: "sensor",
      color: STARTER_RADAR_PROFILE_COLOR,
      notes: "Low-band long-range surveillance radar emphasizing long detection range and reduced sensitivity to shaping, at the cost of coarser track quality.",
      rf: { frequencyMHz: 180, bandwidthKHz: 3000, modulation: "Pulse", waveform: "Low-Band Search", duplex: "simplex", channelSpacingKHz: 1000 },
      tx: { powerW: 600000, dutyCycle: 0.12, papr: 0, spectralEfficiency: null },
      rx: { sensitivityDbm: -106, noiseFigDb: 3, requiredSnrDb: 10, acrDb: 75, bdrDb: 88 },
      antenna: { type: "array", gainDbi: 24, pattern: "sectoral", polarization: "horizontal", heightM: 18, cableLossDb: 1.5, systemLossDb: 4.5 },
      prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
      network: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 180, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
    },
  },
  {
    key: "3d-acquisition-radar",
    name: "3D Acquisition Radar",
    profile: {
      type: "sensor",
      emitterLabel: "3D Acquisition Radar",
      force: "enemy",
      icon: "sensor",
      color: STARTER_RADAR_PROFILE_COLOR,
      notes: "Altitude-capable surveillance and track-initiation radar for medium-to-long-range air defense batteries.",
      rf: { frequencyMHz: 2900, bandwidthKHz: 6000, modulation: "Pulse-Doppler", waveform: "3D Search", duplex: "simplex", channelSpacingKHz: 2500 },
      tx: { powerW: 320000, dutyCycle: 0.16, papr: 0, spectralEfficiency: null },
      rx: { sensitivityDbm: -102, noiseFigDb: 4, requiredSnrDb: 12, acrDb: 78, bdrDb: 88 },
      antenna: { type: "phased-array", gainDbi: 31, pattern: "sectoral", polarization: "linear", heightM: 12, cableLossDb: 1, systemLossDb: 3.5 },
      prop: { model: "itu-p526", clutter: "suburban", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
      network: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 90, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
    },
  },
  {
    key: "mobile-sector-search-radar",
    name: "Mobile Sector Search Radar",
    profile: {
      type: "sensor",
      emitterLabel: "Mobile Sector Search Radar",
      force: "enemy",
      icon: "sensor",
      color: STARTER_RADAR_PROFILE_COLOR,
      notes: "Truck-mobile sector search radar for rapid emplacement, gap coverage, and cueing of nearby air-defense elements.",
      rf: { frequencyMHz: 5600, bandwidthKHz: 4500, modulation: "Pulse-Doppler", waveform: "Sector Search", duplex: "simplex", channelSpacingKHz: 2000 },
      tx: { powerW: 140000, dutyCycle: 0.14, papr: 0, spectralEfficiency: null },
      rx: { sensitivityDbm: -100, noiseFigDb: 4.5, requiredSnrDb: 11, acrDb: 72, bdrDb: 84 },
      antenna: { type: "phased-array", gainDbi: 29, pattern: "directional", polarization: "linear", heightM: 10, cableLossDb: 0.8, systemLossDb: 3.2 },
      prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
      network: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 70, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
    },
  },
  {
    key: "long-range-aesa-surveillance-radar",
    name: "Long-Range AESA Surveillance Radar",
    profile: {
      type: "sensor",
      emitterLabel: "Long-Range AESA Surveillance Radar",
      force: "enemy",
      icon: "sensor",
      color: STARTER_RADAR_PROFILE_COLOR,
      notes: "Modern electronically scanned long-range surveillance radar emphasizing rapid revisit rates, target density handling, and all-weather tracking.",
      rf: { frequencyMHz: 3400, bandwidthKHz: 10000, modulation: "Pulse-Doppler", waveform: "AESA Search", duplex: "simplex", channelSpacingKHz: 5000 },
      tx: { powerW: 280000, dutyCycle: 0.2, papr: 0, spectralEfficiency: null },
      rx: { sensitivityDbm: -101, noiseFigDb: 3.5, requiredSnrDb: 12, acrDb: 82, bdrDb: 90 },
      antenna: { type: "AESA", gainDbi: 35, pattern: "sectoral", polarization: "linear", heightM: 13, cableLossDb: 0.7, systemLossDb: 3.5 },
      prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
      network: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 60, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
    },
  },
  {
    key: "sam-target-acquisition-radar",
    name: "SAM Target Acquisition Radar",
    profile: {
      type: "sensor",
      emitterLabel: "SAM Target Acquisition Radar",
      force: "enemy",
      icon: "sensor",
      color: STARTER_RADAR_PROFILE_COLOR,
      notes: "Battery-level target acquisition radar used to search, classify, and hand off tracks to engagement and command elements.",
      rf: { frequencyMHz: 2700, bandwidthKHz: 5000, modulation: "Pulse-Doppler", waveform: "Acquisition Search", duplex: "simplex", channelSpacingKHz: 2500 },
      tx: { powerW: 210000, dutyCycle: 0.15, papr: 0, spectralEfficiency: null },
      rx: { sensitivityDbm: -101, noiseFigDb: 4, requiredSnrDb: 11, acrDb: 76, bdrDb: 86 },
      antenna: { type: "phased-array", gainDbi: 30, pattern: "sectoral", polarization: "linear", heightM: 11, cableLossDb: 0.9, systemLossDb: 3.4 },
      prop: { model: "itu-p526", clutter: "suburban", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
      network: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 80, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
    },
  },
  {
    key: "sam-engagement-radar",
    name: "SAM Engagement Radar",
    profile: {
      type: "sensor",
      emitterLabel: "SAM Engagement Radar",
      force: "enemy",
      icon: "sensor",
      color: STARTER_RADAR_PROFILE_COLOR,
      notes: "High-gain engagement radar for precision target tracking, missile uplink support, and terminal fire-control tasking.",
      rf: { frequencyMHz: 9300, bandwidthKHz: 2500, modulation: "Pulse-Doppler", waveform: "Target Track", duplex: "simplex", channelSpacingKHz: 1000 },
      tx: { powerW: 95000, dutyCycle: 0.1, papr: 0, spectralEfficiency: null },
      rx: { sensitivityDbm: -98, noiseFigDb: 5, requiredSnrDb: 14, acrDb: 85, bdrDb: 92 },
      antenna: { type: "phased-array", gainDbi: 38, pattern: "directional", polarization: "linear", heightM: 9, cableLossDb: 0.7, systemLossDb: 3 },
      prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
      network: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 45, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
    },
  },
  {
    key: "missile-track-illumination-radar",
    name: "Missile Track / Illumination Radar",
    profile: {
      type: "sensor",
      emitterLabel: "Missile Track / Illumination Radar",
      force: "enemy",
      icon: "sensor",
      color: STARTER_RADAR_PROFILE_COLOR,
      notes: "Narrow-beam fire-control radar for terminal target illumination, missile track support, and high-precision engagement updates.",
      rf: { frequencyMHz: 10300, bandwidthKHz: 1500, modulation: "CW", waveform: "CW Illumination", duplex: "simplex", channelSpacingKHz: 500 },
      tx: { powerW: 70000, dutyCycle: 0.35, papr: 0, spectralEfficiency: null },
      rx: { sensitivityDbm: -96, noiseFigDb: 5, requiredSnrDb: 15, acrDb: 88, bdrDb: 94 },
      antenna: { type: "dish", gainDbi: 41, pattern: "directional", polarization: "linear", heightM: 8, cableLossDb: 0.9, systemLossDb: 3.3 },
      prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
      network: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 35, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
    },
  },
  {
    key: "shorad-fire-control-radar",
    name: "SHORAD Fire-Control Radar",
    profile: {
      type: "sensor",
      emitterLabel: "SHORAD Fire-Control Radar",
      force: "enemy",
      icon: "sensor",
      color: STARTER_RADAR_PROFILE_COLOR,
      notes: "Short-range fire-control radar supporting mobile SHORAD batteries against helicopters, low flyers, and pop-up threats.",
      rf: { frequencyMHz: 15700, bandwidthKHz: 1800, modulation: "Pulse-Doppler", waveform: "SHORAD Track", duplex: "simplex", channelSpacingKHz: 750 },
      tx: { powerW: 45000, dutyCycle: 0.12, papr: 0, spectralEfficiency: null },
      rx: { sensitivityDbm: -97, noiseFigDb: 5.5, requiredSnrDb: 14, acrDb: 84, bdrDb: 90 },
      antenna: { type: "AESA", gainDbi: 36, pattern: "directional", polarization: "linear", heightM: 6, cableLossDb: 0.6, systemLossDb: 2.8 },
      prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
      network: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 30, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
    },
  },
  {
    key: "low-altitude-gap-filler-radar",
    name: "Low-Altitude Gap-Filler Radar",
    profile: {
      type: "sensor",
      emitterLabel: "Low-Altitude Gap-Filler Radar",
      force: "enemy",
      icon: "sensor",
      color: STARTER_RADAR_PROFILE_COLOR,
      notes: "Medium-range low-altitude surveillance radar intended to cover terrain-mask corridors and hand off low-flying targets to nearby batteries.",
      rf: { frequencyMHz: 5400, bandwidthKHz: 4200, modulation: "Pulse-Doppler", waveform: "Gap Filler Search", duplex: "simplex", channelSpacingKHz: 1800 },
      tx: { powerW: 90000, dutyCycle: 0.16, papr: 0, spectralEfficiency: null },
      rx: { sensitivityDbm: -99, noiseFigDb: 4.5, requiredSnrDb: 11, acrDb: 73, bdrDb: 84 },
      antenna: { type: "phased-array", gainDbi: 28, pattern: "sectoral", polarization: "linear", heightM: 9, cableLossDb: 0.8, systemLossDb: 3.1 },
      prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
      network: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 55, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
    },
  },
  {
    key: "counter-uas-surveillance-radar",
    name: "Counter-UAS Surveillance Radar",
    profile: {
      type: "sensor",
      emitterLabel: "Counter-UAS Surveillance Radar",
      force: "enemy",
      icon: "sensor",
      color: STARTER_RADAR_PROFILE_COLOR,
      notes: "Local-area surveillance radar optimized for small, slow, low targets and short revisit times around defended points.",
      rf: { frequencyMHz: 9500, bandwidthKHz: 12000, modulation: "Pulse-Doppler", waveform: "Counter-UAS Search", duplex: "simplex", channelSpacingKHz: 4000 },
      tx: { powerW: 18000, dutyCycle: 0.22, papr: 0, spectralEfficiency: null },
      rx: { sensitivityDbm: -95, noiseFigDb: 5, requiredSnrDb: 10, acrDb: 68, bdrDb: 80 },
      antenna: { type: "AESA", gainDbi: 30, pattern: "sectoral", polarization: "linear", heightM: 5, cableLossDb: 0.5, systemLossDb: 2.5 },
      prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
      network: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 20, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
    },
  },
  {
    key: "passive-air-surveillance-receiver-site",
    name: "Passive Air-Surveillance Receiver Site",
    profile: {
      type: "sensor",
      emitterLabel: "Passive Air-Surveillance Receiver Site",
      force: "enemy",
      icon: "sensor",
      color: STARTER_RADAR_PROFILE_COLOR,
      notes: "Passive DF and ESM-style site that contributes to the air picture without intentional RF transmission; use for bearing-only or emitter-cueing scenarios.",
      rf: { frequencyMHz: 1200, bandwidthKHz: 25000, modulation: "Passive", waveform: "Passive DF", duplex: "simplex", channelSpacingKHz: 5000 },
      tx: { powerW: 0, dutyCycle: 0, papr: 0, spectralEfficiency: null },
      rx: { sensitivityDbm: -112, noiseFigDb: 3, requiredSnrDb: 6, acrDb: 70, bdrDb: 86 },
      antenna: { type: "interferometer", gainDbi: 18, pattern: "omnidirectional", polarization: "linear", heightM: 7, cableLossDb: 0.6, systemLossDb: 2.2 },
      prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
      network: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 25, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
    },
  },
];

function buildStarterEmitterProfiles() {
  return STARTER_RADAR_PROFILE_DEFINITIONS.map((entry) => ({
    key: entry.key,
    name: entry.name,
    profile: emitterProfilePayloadSchema.parse({
      radioType: "",
      programKey: "",
      locationDefaults: {
        gridLocation: "",
        colocateAssetId: "",
      },
      ...entry.profile,
    }),
  }));
}

module.exports = {
  STARTER_RADAR_PROFILE_DEFINITIONS,
  buildStarterEmitterProfiles,
};
