// Extracted from app.js to shrink the eager entry module and create a stable feature seam.
// The emitter editor loads this module on first use.

const RADAR_EMITTER_LIBRARY = {
  "long-range-early-warning-radar": {
    label: "Long-Range Early Warning Radar",
    programs: {
      default: {
        label: "Volume Search",
        type: "sensor",
        force: "enemy",
        icon: "sensor",
        color: "#ef4444",
        notes: "Broad-area long-range surveillance radar optimized for wide azimuth coverage and early warning against aircraft and cruise-missile sized targets.",
        rf: { frequencyMHz: 1250, bandwidthKHz: 8000, modulation: "Pulse", waveform: "Volume Search", duplex: "simplex", channelSpacingKHz: 5000 },
        tx: { powerW: 850000, dutyCycle: 0.18, papr: 0, spectralEfficiency: null },
        rx: { sensitivityDbm: -103, noiseFigDb: 4, requiredSnrDb: 13, acrDb: 80, bdrDb: 90 },
        antenna: { type: "phased-array", gainDbi: 33, pattern: "sectoral", polarization: "linear", heightM: 14, cableLossDb: 1.2, systemLossDb: 4 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 120, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
      },
    },
  },
  "vhf-early-warning-radar": {
    label: "VHF Early Warning Radar",
    programs: {
      default: {
        label: "Low-Band Search",
        type: "sensor",
        force: "enemy",
        icon: "sensor",
        color: "#ef4444",
        notes: "Low-band long-range surveillance radar emphasizing long detection range and reduced sensitivity to shaping, at the cost of coarser track quality.",
        rf: { frequencyMHz: 180, bandwidthKHz: 3000, modulation: "Pulse", waveform: "Low-Band Search", duplex: "simplex", channelSpacingKHz: 1000 },
        tx: { powerW: 600000, dutyCycle: 0.12, papr: 0, spectralEfficiency: null },
        rx: { sensitivityDbm: -106, noiseFigDb: 3, requiredSnrDb: 10, acrDb: 75, bdrDb: 88 },
        antenna: { type: "array", gainDbi: 24, pattern: "sectoral", polarization: "horizontal", heightM: 18, cableLossDb: 1.5, systemLossDb: 4.5 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 180, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
      },
    },
  },
  "3d-acquisition-radar": {
    label: "3D Acquisition Radar",
    programs: {
      default: {
        label: "3D Search",
        type: "sensor",
        force: "enemy",
        icon: "sensor",
        color: "#ef4444",
        notes: "Altitude-capable surveillance and track-initiation radar for medium-to-long-range air defense batteries.",
        rf: { frequencyMHz: 2900, bandwidthKHz: 6000, modulation: "Pulse-Doppler", waveform: "3D Search", duplex: "simplex", channelSpacingKHz: 2500 },
        tx: { powerW: 320000, dutyCycle: 0.16, papr: 0, spectralEfficiency: null },
        rx: { sensitivityDbm: -102, noiseFigDb: 4, requiredSnrDb: 12, acrDb: 78, bdrDb: 88 },
        antenna: { type: "phased-array", gainDbi: 31, pattern: "sectoral", polarization: "linear", heightM: 12, cableLossDb: 1, systemLossDb: 3.5 },
        prop: { model: "itu-p526", clutter: "suburban", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 90, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
      },
    },
  },
  "mobile-sector-search-radar": {
    label: "Mobile Sector Search Radar",
    programs: {
      default: {
        label: "Sector Search",
        type: "sensor",
        force: "enemy",
        icon: "sensor",
        color: "#ef4444",
        notes: "Truck-mobile sector search radar for rapid emplacement, gap coverage, and cueing of nearby air-defense elements.",
        rf: { frequencyMHz: 5600, bandwidthKHz: 4500, modulation: "Pulse-Doppler", waveform: "Sector Search", duplex: "simplex", channelSpacingKHz: 2000 },
        tx: { powerW: 140000, dutyCycle: 0.14, papr: 0, spectralEfficiency: null },
        rx: { sensitivityDbm: -100, noiseFigDb: 4.5, requiredSnrDb: 11, acrDb: 72, bdrDb: 84 },
        antenna: { type: "phased-array", gainDbi: 29, pattern: "directional", polarization: "linear", heightM: 10, cableLossDb: 0.8, systemLossDb: 3.2 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 70, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
      },
    },
  },
  "long-range-aesa-surveillance-radar": {
    label: "Long-Range AESA Surveillance Radar",
    programs: {
      default: {
        label: "AESA Search",
        type: "sensor",
        force: "enemy",
        icon: "sensor",
        color: "#ef4444",
        notes: "Modern electronically scanned long-range surveillance radar emphasizing rapid revisit rates, target density handling, and all-weather tracking.",
        rf: { frequencyMHz: 3400, bandwidthKHz: 10000, modulation: "Pulse-Doppler", waveform: "AESA Search", duplex: "simplex", channelSpacingKHz: 5000 },
        tx: { powerW: 280000, dutyCycle: 0.2, papr: 0, spectralEfficiency: null },
        rx: { sensitivityDbm: -101, noiseFigDb: 3.5, requiredSnrDb: 12, acrDb: 82, bdrDb: 90 },
        antenna: { type: "AESA", gainDbi: 35, pattern: "sectoral", polarization: "linear", heightM: 13, cableLossDb: 0.7, systemLossDb: 3.5 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 60, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
      },
    },
  },
  "sam-target-acquisition-radar": {
    label: "SAM Target Acquisition Radar",
    programs: {
      default: {
        label: "Acquisition Search",
        type: "sensor",
        force: "enemy",
        icon: "sensor",
        color: "#ef4444",
        notes: "Battery-level target acquisition radar used to search, classify, and hand off tracks to engagement and command elements.",
        rf: { frequencyMHz: 2700, bandwidthKHz: 5000, modulation: "Pulse-Doppler", waveform: "Acquisition Search", duplex: "simplex", channelSpacingKHz: 2500 },
        tx: { powerW: 210000, dutyCycle: 0.15, papr: 0, spectralEfficiency: null },
        rx: { sensitivityDbm: -101, noiseFigDb: 4, requiredSnrDb: 11, acrDb: 76, bdrDb: 86 },
        antenna: { type: "phased-array", gainDbi: 30, pattern: "sectoral", polarization: "linear", heightM: 11, cableLossDb: 0.9, systemLossDb: 3.4 },
        prop: { model: "itu-p526", clutter: "suburban", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 80, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
      },
    },
  },
  "sam-engagement-radar": {
    label: "SAM Engagement Radar",
    programs: {
      default: {
        label: "Target Track",
        type: "sensor",
        force: "enemy",
        icon: "sensor",
        color: "#ef4444",
        notes: "High-gain engagement radar for precision target tracking, missile uplink support, and terminal fire-control tasking.",
        rf: { frequencyMHz: 9300, bandwidthKHz: 2500, modulation: "Pulse-Doppler", waveform: "Target Track", duplex: "simplex", channelSpacingKHz: 1000 },
        tx: { powerW: 95000, dutyCycle: 0.1, papr: 0, spectralEfficiency: null },
        rx: { sensitivityDbm: -98, noiseFigDb: 5, requiredSnrDb: 14, acrDb: 85, bdrDb: 92 },
        antenna: { type: "phased-array", gainDbi: 38, pattern: "directional", polarization: "linear", heightM: 9, cableLossDb: 0.7, systemLossDb: 3 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 45, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
      },
    },
  },
  "missile-track-illumination-radar": {
    label: "Missile Track / Illumination Radar",
    programs: {
      default: {
        label: "CW Illumination",
        type: "sensor",
        force: "enemy",
        icon: "sensor",
        color: "#ef4444",
        notes: "Narrow-beam fire-control radar for terminal target illumination, missile track support, and high-precision engagement updates.",
        rf: { frequencyMHz: 10300, bandwidthKHz: 1500, modulation: "CW", waveform: "CW Illumination", duplex: "simplex", channelSpacingKHz: 500 },
        tx: { powerW: 70000, dutyCycle: 0.35, papr: 0, spectralEfficiency: null },
        rx: { sensitivityDbm: -96, noiseFigDb: 5, requiredSnrDb: 15, acrDb: 88, bdrDb: 94 },
        antenna: { type: "dish", gainDbi: 41, pattern: "directional", polarization: "linear", heightM: 8, cableLossDb: 0.9, systemLossDb: 3.3 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 35, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
      },
    },
  },
  "shorad-fire-control-radar": {
    label: "SHORAD Fire-Control Radar",
    programs: {
      default: {
        label: "SHORAD Track",
        type: "sensor",
        force: "enemy",
        icon: "sensor",
        color: "#ef4444",
        notes: "Short-range fire-control radar supporting mobile SHORAD batteries against helicopters, low flyers, and pop-up threats.",
        rf: { frequencyMHz: 15700, bandwidthKHz: 1800, modulation: "Pulse-Doppler", waveform: "SHORAD Track", duplex: "simplex", channelSpacingKHz: 750 },
        tx: { powerW: 45000, dutyCycle: 0.12, papr: 0, spectralEfficiency: null },
        rx: { sensitivityDbm: -97, noiseFigDb: 5.5, requiredSnrDb: 14, acrDb: 84, bdrDb: 90 },
        antenna: { type: "AESA", gainDbi: 36, pattern: "directional", polarization: "linear", heightM: 6, cableLossDb: 0.6, systemLossDb: 2.8 },
        prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 30, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
      },
    },
  },
  "low-altitude-gap-filler-radar": {
    label: "Low-Altitude Gap-Filler Radar",
    programs: {
      default: {
        label: "Gap Filler Search",
        type: "sensor",
        force: "enemy",
        icon: "sensor",
        color: "#ef4444",
        notes: "Medium-range low-altitude surveillance radar intended to cover terrain-mask corridors and hand off low-flying targets to nearby batteries.",
        rf: { frequencyMHz: 5400, bandwidthKHz: 4200, modulation: "Pulse-Doppler", waveform: "Gap Filler Search", duplex: "simplex", channelSpacingKHz: 1800 },
        tx: { powerW: 90000, dutyCycle: 0.16, papr: 0, spectralEfficiency: null },
        rx: { sensitivityDbm: -99, noiseFigDb: 4.5, requiredSnrDb: 11, acrDb: 73, bdrDb: 84 },
        antenna: { type: "phased-array", gainDbi: 28, pattern: "sectoral", polarization: "linear", heightM: 9, cableLossDb: 0.8, systemLossDb: 3.1 },
        prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 55, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
      },
    },
  },
  "counter-uas-surveillance-radar": {
    label: "Counter-UAS Surveillance Radar",
    programs: {
      default: {
        label: "Counter-UAS Search",
        type: "sensor",
        force: "enemy",
        icon: "sensor",
        color: "#ef4444",
        notes: "Local-area surveillance radar optimized for small, slow, low targets and short revisit times around defended points.",
        rf: { frequencyMHz: 9500, bandwidthKHz: 12000, modulation: "Pulse-Doppler", waveform: "Counter-UAS Search", duplex: "simplex", channelSpacingKHz: 4000 },
        tx: { powerW: 18000, dutyCycle: 0.22, papr: 0, spectralEfficiency: null },
        rx: { sensitivityDbm: -95, noiseFigDb: 5, requiredSnrDb: 10, acrDb: 68, bdrDb: 80 },
        antenna: { type: "AESA", gainDbi: 30, pattern: "sectoral", polarization: "linear", heightM: 5, cableLossDb: 0.5, systemLossDb: 2.5 },
        prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 20, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
      },
    },
  },
  "passive-air-surveillance-receiver-site": {
    label: "Passive Air-Surveillance Receiver Site",
    programs: {
      default: {
        label: "Passive DF",
        type: "sensor",
        force: "enemy",
        icon: "sensor",
        color: "#ef4444",
        notes: "Passive DF and ESM-style site that contributes to the air picture without intentional RF transmission; use for bearing-only or emitter-cueing scenarios.",
        rf: { frequencyMHz: 1200, bandwidthKHz: 25000, modulation: "Passive", waveform: "Passive DF", duplex: "simplex", channelSpacingKHz: 5000 },
        tx: { powerW: 0, dutyCycle: 0, papr: 0, spectralEfficiency: null },
        rx: { sensitivityDbm: -112, noiseFigDb: 3, requiredSnrDb: 6, acrDb: 70, bdrDb: 86 },
        antenna: { type: "interferometer", gainDbi: 18, pattern: "omnidirectional", polarization: "linear", heightM: 7, cableLossDb: 0.6, systemLossDb: 2.2 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true, nvisEnabled: false, ionoModel: "simple", timeDayEffects: false, solarIndex: null },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 25, adaptiveDataRate: false, satcomEnabled: false, satType: "", satUplinkMHz: null, satDownlinkMHz: null, satGainDbi: null },
      },
    },
  },
};

const EMITTER_LIBRARY = {
  "prc-163": {
    label: "AN/PRC-163 Falcon IV",
    programs: {
      "vhf-sincgars": {
        label: "VHF LOS â€” SINCGARS",
        rf: { frequencyMHz: 46, bandwidthKHz: 25, modulation: "FHSS", waveform: "SINCGARS", duplex: "half-duplex", channelSpacingKHz: 25 },
        tx: { powerW: 5, dutyCycle: 0.5, papr: 0, spectralEfficiency: 4.8 },
        rx: { sensitivityDbm: -107, noiseFigDb: 6, requiredSnrDb: 12, acrDb: 70, bdrDb: 90 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 2, cableLossDb: 0.5, systemLossDb: 3 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 200, adaptiveDataRate: false },
      },
      "uhf-los": {
        label: "UHF LOS â€” Tactical",
        rf: { frequencyMHz: 370, bandwidthKHz: 25, modulation: "FM", waveform: "analog", duplex: "half-duplex", channelSpacingKHz: 25 },
        tx: { powerW: 5, dutyCycle: 0.5, papr: 0, spectralEfficiency: 2.4 },
        rx: { sensitivityDbm: -107, noiseFigDb: 6, requiredSnrDb: 12, acrDb: 65, bdrDb: 85 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 2, cableLossDb: 0.5, systemLossDb: 3 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 150, adaptiveDataRate: false },
      },
      "srw-manet": {
        label: "SRW MANET â€” Soldier Radio",
        rf: { frequencyMHz: 2400, bandwidthKHz: 5000, modulation: "OFDM", waveform: "SRW", duplex: "full-duplex", channelSpacingKHz: 5000 },
        tx: { powerW: 2, dutyCycle: 1, papr: 8, spectralEfficiency: 1.5 },
        rx: { sensitivityDbm: -95, noiseFigDb: 8, requiredSnrDb: 10, acrDb: 30, bdrDb: 60 },
        antenna: { type: "blade", gainDbi: 0, pattern: "omnidirectional", polarization: "vertical", heightM: 1.5, cableLossDb: 0.3, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: true, relayCapable: true, maxHops: 8, latencyMs: 50, adaptiveDataRate: true },
      },
      "muos-satcom": {
        label: "MUOS SATCOM â€” WCDMA",
        rf: { frequencyMHz: 300, bandwidthKHz: 5000, modulation: "QPSK", waveform: "MUOS", duplex: "full-duplex", channelSpacingKHz: 5000 },
        tx: { powerW: 20, dutyCycle: 1, papr: 6, spectralEfficiency: 2 },
        rx: { sensitivityDbm: -107, noiseFigDb: 4, requiredSnrDb: 8, acrDb: 60, bdrDb: 80 },
        antenna: { type: "satcom_patch", gainDbi: 10, pattern: "directional", polarization: "circular", heightM: 1.5, cableLossDb: 1, systemLossDb: 4 },
        prop: { model: "itu-p528", clutter: "open", terrainEnabled: false, diffractionEnabled: false },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 600, adaptiveDataRate: true, satcomEnabled: true, satType: "GEO", satUplinkMHz: 292, satDownlinkMHz: 243, satGainDbi: 10 },
      },
    },
  },
  "prc-152a": {
    label: "AN/PRC-152A Falcon III",
    programs: {
      "vhf-los": {
        label: "VHF LOS â€” SINCGARS",
        rf: { frequencyMHz: 60, bandwidthKHz: 25, modulation: "FHSS", waveform: "SINCGARS", duplex: "half-duplex", channelSpacingKHz: 25 },
        tx: { powerW: 5, dutyCycle: 0.5, papr: 0, spectralEfficiency: 4.8 },
        rx: { sensitivityDbm: -107, noiseFigDb: 6, requiredSnrDb: 12, acrDb: 70, bdrDb: 90 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 2, cableLossDb: 0.5, systemLossDb: 3 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 200, adaptiveDataRate: false },
      },
      "anw2": {
        label: "ANW2 MANET",
        rf: { frequencyMHz: 1800, bandwidthKHz: 2000, modulation: "OFDM", waveform: "ANW2", duplex: "full-duplex", channelSpacingKHz: 2000 },
        tx: { powerW: 5, dutyCycle: 1, papr: 6, spectralEfficiency: 2 },
        rx: { sensitivityDbm: -98, noiseFigDb: 7, requiredSnrDb: 10, acrDb: 40, bdrDb: 70 },
        antenna: { type: "blade", gainDbi: 0, pattern: "omnidirectional", polarization: "vertical", heightM: 2, cableLossDb: 0.5, systemLossDb: 3 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: true, relayCapable: true, maxHops: 6, latencyMs: 80, adaptiveDataRate: true },
      },
    },
  },
  "prc-117g": {
    label: "AN/PRC-117G Falcon III",
    programs: {
      "vhf-cmd": {
        label: "VHF Command Net",
        rf: { frequencyMHz: 50, bandwidthKHz: 25, modulation: "FM", waveform: "analog", duplex: "half-duplex", channelSpacingKHz: 25 },
        tx: { powerW: 20, dutyCycle: 0.5, papr: 0, spectralEfficiency: 2.4 },
        rx: { sensitivityDbm: -107, noiseFigDb: 5, requiredSnrDb: 12, acrDb: 70, bdrDb: 90 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 2, cableLossDb: 0.5, systemLossDb: 3 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: true, maxHops: 1, latencyMs: 200, adaptiveDataRate: false },
      },
      "uhf-satcom-dama": {
        label: "UHF SATCOM DAMA",
        rf: { frequencyMHz: 305, bandwidthKHz: 25, modulation: "PSK", waveform: "MUOS", duplex: "full-duplex", channelSpacingKHz: 25 },
        tx: { powerW: 20, dutyCycle: 1, papr: 3, spectralEfficiency: 1.2 },
        rx: { sensitivityDbm: -107, noiseFigDb: 4, requiredSnrDb: 8, acrDb: 60, bdrDb: 80 },
        antenna: { type: "satcom_patch", gainDbi: 10, pattern: "directional", polarization: "circular", heightM: 1.5, cableLossDb: 1, systemLossDb: 4 },
        prop: { model: "itu-p528", clutter: "open", terrainEnabled: false, diffractionEnabled: false },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 600, adaptiveDataRate: false, satcomEnabled: true, satType: "GEO", satUplinkMHz: 305, satDownlinkMHz: 255, satGainDbi: 10 },
      },
      "wb-anw2": {
        label: "Wideband ANW2",
        rf: { frequencyMHz: 1500, bandwidthKHz: 5000, modulation: "OFDM", waveform: "ANW2", duplex: "full-duplex", channelSpacingKHz: 5000 },
        tx: { powerW: 20, dutyCycle: 1, papr: 8, spectralEfficiency: 3 },
        rx: { sensitivityDbm: -95, noiseFigDb: 6, requiredSnrDb: 10, acrDb: 40, bdrDb: 75 },
        antenna: { type: "blade", gainDbi: 2, pattern: "omnidirectional", polarization: "vertical", heightM: 2, cableLossDb: 0.5, systemLossDb: 3 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: true, relayCapable: true, maxHops: 6, latencyMs: 60, adaptiveDataRate: true },
      },
    },
  },
  "prc-160": {
    label: "AN/PRC-160",
    programs: {
      "hf-nvis": {
        label: "HF NVIS â€” Short Range",
        rf: { frequencyMHz: 5.5, bandwidthKHz: 3, modulation: "USB", waveform: "ALE", duplex: "half-duplex", channelSpacingKHz: 3 },
        tx: { powerW: 20, dutyCycle: 0.5, papr: 0, spectralEfficiency: 0.4 },
        rx: { sensitivityDbm: -110, noiseFigDb: 10, requiredSnrDb: 6, acrDb: 60, bdrDb: 90 },
        antenna: { type: "dipole", gainDbi: 2, pattern: "omnidirectional", polarization: "horizontal", heightM: 5, cableLossDb: 0.5, systemLossDb: 2 },
        prop: { model: "hf-skywave", clutter: "open", terrainEnabled: false, diffractionEnabled: false, nvisEnabled: true, ionoModel: "itu-r", timeDayEffects: true, solarIndex: 80 },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 500, adaptiveDataRate: false },
      },
      "hf-longhaul": {
        label: "HF Long-Haul â€” Skywave",
        rf: { frequencyMHz: 14, bandwidthKHz: 3, modulation: "USB", waveform: "ALE", duplex: "half-duplex", channelSpacingKHz: 3 },
        tx: { powerW: 20, dutyCycle: 0.5, papr: 0, spectralEfficiency: 0.4 },
        rx: { sensitivityDbm: -110, noiseFigDb: 10, requiredSnrDb: 6, acrDb: 60, bdrDb: 90 },
        antenna: { type: "dipole", gainDbi: 2, pattern: "directional", polarization: "horizontal", heightM: 8, cableLossDb: 1, systemLossDb: 3 },
        prop: { model: "hf-skywave", clutter: "open", terrainEnabled: false, diffractionEnabled: false, nvisEnabled: false, ionoModel: "itu-r", timeDayEffects: true, solarIndex: 80 },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 800, adaptiveDataRate: false },
      },
      "vhf-fallback": {
        label: "VHF Fallback â€” Analog",
        rf: { frequencyMHz: 50, bandwidthKHz: 25, modulation: "FM", waveform: "analog", duplex: "half-duplex", channelSpacingKHz: 25 },
        tx: { powerW: 5, dutyCycle: 0.5, papr: 0, spectralEfficiency: 2.4 },
        rx: { sensitivityDbm: -107, noiseFigDb: 6, requiredSnrDb: 12, acrDb: 70, bdrDb: 90 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 2, cableLossDb: 0.5, systemLossDb: 3 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 200, adaptiveDataRate: false },
      },
    },
  },
  "mbitr": {
    label: "AN/PRC-148 MBITR",
    programs: {
      "vhf-los": {
        label: "VHF LOS",
        rf: { frequencyMHz: 150, bandwidthKHz: 25, modulation: "FM", waveform: "analog", duplex: "half-duplex", channelSpacingKHz: 25 },
        tx: { powerW: 5, dutyCycle: 0.5, papr: 0, spectralEfficiency: 2.4 },
        rx: { sensitivityDbm: -107, noiseFigDb: 7, requiredSnrDb: 12, acrDb: 65, bdrDb: 85 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 2, cableLossDb: 0.5, systemLossDb: 3 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 200, adaptiveDataRate: false },
      },
    },
  },
  "p25-portable": {
    label: "P25 Portable (generic)",
    programs: {
      "p25-ph1-vhf": {
        label: "P25 Phase 1 VHF",
        rf: { frequencyMHz: 155, bandwidthKHz: 12.5, modulation: "FM", waveform: "P25-C4FM", duplex: "half-duplex", channelSpacingKHz: 12.5 },
        tx: { powerW: 5, dutyCycle: 0.5, papr: 0, spectralEfficiency: 4.8 },
        rx: { sensitivityDbm: -116, noiseFigDb: 5, requiredSnrDb: 12, acrDb: 70, bdrDb: 90 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 1.8, cableLossDb: 0.3, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 100, adaptiveDataRate: false },
      },
      "p25-ph1-uhf": {
        label: "P25 Phase 1 UHF",
        rf: { frequencyMHz: 460, bandwidthKHz: 12.5, modulation: "FM", waveform: "P25-CQPSK", duplex: "half-duplex", channelSpacingKHz: 12.5 },
        tx: { powerW: 4, dutyCycle: 0.5, papr: 0, spectralEfficiency: 4.8 },
        rx: { sensitivityDbm: -116, noiseFigDb: 5, requiredSnrDb: 12, acrDb: 70, bdrDb: 90 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 1.8, cableLossDb: 0.3, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 100, adaptiveDataRate: false },
      },
      "p25-ph2-tdma": {
        label: "P25 Phase 2 TDMA",
        rf: { frequencyMHz: 460, bandwidthKHz: 12.5, modulation: "QPSK", waveform: "P25-TDMA", duplex: "half-duplex", channelSpacingKHz: 12.5 },
        tx: { powerW: 4, dutyCycle: 0.5, papr: 3, spectralEfficiency: 9.6 },
        rx: { sensitivityDbm: -116, noiseFigDb: 5, requiredSnrDb: 12, acrDb: 70, bdrDb: 90 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 1.8, cableLossDb: 0.3, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 80, adaptiveDataRate: false },
      },
    },
  },
  "p25-mobile": {
    label: "P25 Mobile (generic)",
    programs: {
      "p25-vhf-mobile": {
        label: "P25 VHF Mobile",
        rf: { frequencyMHz: 155, bandwidthKHz: 12.5, modulation: "FM", waveform: "P25-C4FM", duplex: "half-duplex", channelSpacingKHz: 12.5 },
        tx: { powerW: 50, dutyCycle: 0.5, papr: 0, spectralEfficiency: 4.8 },
        rx: { sensitivityDbm: -116, noiseFigDb: 4, requiredSnrDb: 12, acrDb: 75, bdrDb: 95 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 1.5, cableLossDb: 1, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "suburban", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 100, adaptiveDataRate: false },
      },
    },
  },
  "p25-repeater": {
    label: "P25 Repeater",
    programs: {
      "vhf-repeat": {
        label: "VHF Repeater",
        rf: { frequencyMHz: 155, bandwidthKHz: 12.5, modulation: "FM", waveform: "P25-C4FM", duplex: "full-duplex", channelSpacingKHz: 12.5 },
        tx: { powerW: 100, dutyCycle: 1, papr: 0, spectralEfficiency: 4.8 },
        rx: { sensitivityDbm: -120, noiseFigDb: 3, requiredSnrDb: 12, acrDb: 80, bdrDb: 100 },
        antenna: { type: "dipole", gainDbi: 6, pattern: "omnidirectional", polarization: "vertical", heightM: 30, cableLossDb: 2, systemLossDb: 3 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: true, maxHops: 1, latencyMs: 50, adaptiveDataRate: false },
      },
    },
  },
  // â”€â”€ Commercial DMR â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
  "dmr-portable": {
    label: "DMR Portable (Tier II)",
    programs: {
      "dmr-uhf": {
        label: "DMR UHF Direct",
        rf: { frequencyMHz: 460, bandwidthKHz: 12.5, modulation: "QPSK", waveform: "DMR", duplex: "half-duplex", channelSpacingKHz: 12.5 },
        tx: { powerW: 4, dutyCycle: 0.5, papr: 3, spectralEfficiency: 9.6 },
        rx: { sensitivityDbm: -116, noiseFigDb: 5, requiredSnrDb: 12, acrDb: 70, bdrDb: 90 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 1.8, cableLossDb: 0.3, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 80, adaptiveDataRate: false },
      },
    },
  },
  "dmr-mobile": {
    label: "DMR Mobile (Tier II)",
    programs: {
      "dmr-uhf-mobile": {
        label: "DMR UHF Mobile",
        rf: { frequencyMHz: 460, bandwidthKHz: 12.5, modulation: "QPSK", waveform: "DMR", duplex: "half-duplex", channelSpacingKHz: 12.5 },
        tx: { powerW: 25, dutyCycle: 0.5, papr: 3, spectralEfficiency: 9.6 },
        rx: { sensitivityDbm: -116, noiseFigDb: 4, requiredSnrDb: 12, acrDb: 75, bdrDb: 95 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 1.5, cableLossDb: 1, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "suburban", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 80, adaptiveDataRate: false },
      },
    },
  },
  "dmr-repeater": {
    label: "DMR Repeater (Tier III)",
    programs: {
      "dmr-tier3": {
        label: "DMR Trunked Repeater",
        rf: { frequencyMHz: 460, bandwidthKHz: 12.5, modulation: "QPSK", waveform: "DMR", duplex: "full-duplex", channelSpacingKHz: 12.5 },
        tx: { powerW: 100, dutyCycle: 1, papr: 3, spectralEfficiency: 9.6 },
        rx: { sensitivityDbm: -120, noiseFigDb: 3, requiredSnrDb: 12, acrDb: 80, bdrDb: 100 },
        antenna: { type: "dipole", gainDbi: 6, pattern: "omnidirectional", polarization: "vertical", heightM: 30, cableLossDb: 2, systemLossDb: 3 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: true, maxHops: 1, latencyMs: 50, adaptiveDataRate: true },
      },
    },
  },
  "mototrbo-r7": {
    label: "Motorola MOTOTRBO R7",
    programs: {
      "dmr-vhf": {
        label: "DMR VHF",
        rf: { frequencyMHz: 155, bandwidthKHz: 12.5, modulation: "QPSK", waveform: "DMR", duplex: "half-duplex", channelSpacingKHz: 12.5 },
        tx: { powerW: 5, dutyCycle: 0.5, papr: 3, spectralEfficiency: 9.6 },
        rx: { sensitivityDbm: -118, noiseFigDb: 5, requiredSnrDb: 12, acrDb: 70, bdrDb: 90 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 1.8, cableLossDb: 0.3, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 80, adaptiveDataRate: false },
      },
      "p25-analog": {
        label: "P25 / Analog Fallback",
        rf: { frequencyMHz: 460, bandwidthKHz: 12.5, modulation: "FM", waveform: "P25-C4FM", duplex: "half-duplex", channelSpacingKHz: 12.5 },
        tx: { powerW: 4, dutyCycle: 0.5, papr: 0, spectralEfficiency: 4.8 },
        rx: { sensitivityDbm: -118, noiseFigDb: 5, requiredSnrDb: 12, acrDb: 70, bdrDb: 90 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 1.8, cableLossDb: 0.3, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 100, adaptiveDataRate: false },
      },
    },
  },
  "harris-xg100p": {
    label: "Harris XG-100P (P25/LTE)",
    programs: {
      "p25-uhf": {
        label: "P25 UHF",
        rf: { frequencyMHz: 460, bandwidthKHz: 12.5, modulation: "FM", waveform: "P25-CQPSK", duplex: "half-duplex", channelSpacingKHz: 12.5 },
        tx: { powerW: 5, dutyCycle: 0.5, papr: 0, spectralEfficiency: 4.8 },
        rx: { sensitivityDbm: -116, noiseFigDb: 5, requiredSnrDb: 12, acrDb: 70, bdrDb: 90 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 1.8, cableLossDb: 0.3, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 100, adaptiveDataRate: false },
      },
    },
  },
  "xts-2500": {
    label: "Motorola XTS 2500 (P25)",
    programs: {
      "p25-uhf": {
        label: "P25 Phase 1 UHF",
        rf: { frequencyMHz: 460, bandwidthKHz: 12.5, modulation: "FM", waveform: "P25-C4FM", duplex: "half-duplex", channelSpacingKHz: 12.5 },
        tx: { powerW: 5, dutyCycle: 0.5, papr: 0, spectralEfficiency: 4.8 },
        rx: { sensitivityDbm: -116, noiseFigDb: 5, requiredSnrDb: 12, acrDb: 70, bdrDb: 90 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 1.8, cableLossDb: 0.3, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 100, adaptiveDataRate: false },
      },
      "p25-vhf": {
        label: "P25 Phase 1 VHF",
        rf: { frequencyMHz: 155, bandwidthKHz: 12.5, modulation: "FM", waveform: "P25-C4FM", duplex: "half-duplex", channelSpacingKHz: 12.5 },
        tx: { powerW: 5, dutyCycle: 0.5, papr: 0, spectralEfficiency: 4.8 },
        rx: { sensitivityDbm: -116, noiseFigDb: 5, requiredSnrDb: 12, acrDb: 70, bdrDb: 90 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 1.8, cableLossDb: 0.3, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 100, adaptiveDataRate: false },
      },
      "analog-uhf": {
        label: "Analog Conventional UHF",
        rf: { frequencyMHz: 460, bandwidthKHz: 25, modulation: "FM", waveform: "analog", duplex: "half-duplex", channelSpacingKHz: 25 },
        tx: { powerW: 5, dutyCycle: 0.5, papr: 0, spectralEfficiency: 2.4 },
        rx: { sensitivityDbm: -116, noiseFigDb: 5, requiredSnrDb: 12, acrDb: 70, bdrDb: 90 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 1.8, cableLossDb: 0.3, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 0, adaptiveDataRate: false },
      },
    },
  },

  // â”€â”€ MANET / Mesh Radios â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

  // FPV / UAS Control and Data Links

  "expresslrs": {
    label: "ExpressLRS",
    programs: {
      "2p4-high-rate": {
        label: "2.4 GHz High-Rate RC Link",
        notes: "ExpressLRS control-link profile tuned for low-latency FPV/UAS control on the 2.4 GHz family.",
        rf: { frequencyMHz: 2440, bandwidthKHz: 80000, modulation: "FHSS", waveform: "ELRS 2.4", duplex: "half-duplex", channelSpacingKHz: 1000 },
        tx: { powerW: 1, dutyCycle: 0.5, papr: 2, spectralEfficiency: 1.2 },
        rx: { sensitivityDbm: -105, noiseFigDb: 6, requiredSnrDb: 7, acrDb: 45, bdrDb: 70 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 1.5, cableLossDb: 0.3, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 8, adaptiveDataRate: false },
      },
      "915-long-range": {
        label: "915 MHz Long-Range RC Link",
        notes: "ExpressLRS long-range control-link profile for 915 MHz class systems.",
        rf: { frequencyMHz: 915, bandwidthKHz: 26000, modulation: "FHSS", waveform: "ELRS 900", duplex: "half-duplex", channelSpacingKHz: 500 },
        tx: { powerW: 1, dutyCycle: 0.5, papr: 2, spectralEfficiency: 0.9 },
        rx: { sensitivityDbm: -118, noiseFigDb: 5, requiredSnrDb: 5, acrDb: 50, bdrDb: 75 },
        antenna: { type: "whip", gainDbi: 2.15, pattern: "omnidirectional", polarization: "vertical", heightM: 1.5, cableLossDb: 0.3, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 15, adaptiveDataRate: false },
      },
    },
  },

  "skydio-x10d": {
    label: "Skydio X10D",
    programs: {
      "mh-control-link": {
        label: "MH Control Link",
        notes: "Approximate default for the Microhard-backed X10D MH control and telemetry family.",
        rf: { frequencyMHz: 1430, bandwidthKHz: 5000, modulation: "OFDM", waveform: "Skydio X10D MH", duplex: "full-duplex", channelSpacingKHz: 5000 },
        tx: { powerW: 1, dutyCycle: 1, papr: 7, spectralEfficiency: 2 },
        rx: { sensitivityDbm: -97, noiseFigDb: 6, requiredSnrDb: 8, acrDb: 35, bdrDb: 60 },
        antenna: { type: "patch", gainDbi: 3, pattern: "directional", polarization: "dual", heightM: 1.5, cableLossDb: 0.5, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 40, adaptiveDataRate: true },
      },
      "sl-control-link": {
        label: "SkydioLink Control Link",
        notes: "Approximate default for the SkydioLink 5 GHz control-link family.",
        rf: { frequencyMHz: 5800, bandwidthKHz: 20000, modulation: "OFDM", waveform: "SkydioLink", duplex: "full-duplex", channelSpacingKHz: 20000 },
        tx: { powerW: 1, dutyCycle: 1, papr: 7, spectralEfficiency: 3 },
        rx: { sensitivityDbm: -95, noiseFigDb: 6, requiredSnrDb: 8, acrDb: 35, bdrDb: 60 },
        antenna: { type: "patch", gainDbi: 3, pattern: "directional", polarization: "dual", heightM: 1.5, cableLossDb: 0.5, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 30, adaptiveDataRate: true },
      },
    },
  },

  "microhard-fdr3025": {
    label: "Microhard FDR3025",
    programs: {
      "l-band-fhss": {
        label: "MDDL L-Band FHSS",
        notes: "Approximate single-band view of a multiband Microhard UAS digital data link.",
        rf: { frequencyMHz: 1350, bandwidthKHz: 5000, modulation: "OFDM", waveform: "Microhard MDDL", duplex: "full-duplex", channelSpacingKHz: 5000 },
        tx: { powerW: 1, dutyCycle: 1, papr: 8, spectralEfficiency: 2.5 },
        rx: { sensitivityDbm: -97, noiseFigDb: 6, requiredSnrDb: 8, acrDb: 35, bdrDb: 60 },
        antenna: { type: "omni_dipole", gainDbi: 2, pattern: "omnidirectional", polarization: "vertical", heightM: 1.5, cableLossDb: 0.4, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 25, adaptiveDataRate: true },
      },
      "s-band-fhss": {
        label: "MDDL S-Band FHSS",
        notes: "Approximate single-band view of a multiband Microhard UAS digital data link.",
        rf: { frequencyMHz: 2400, bandwidthKHz: 10000, modulation: "OFDM", waveform: "Microhard MDDL", duplex: "full-duplex", channelSpacingKHz: 10000 },
        tx: { powerW: 1, dutyCycle: 1, papr: 8, spectralEfficiency: 3 },
        rx: { sensitivityDbm: -95, noiseFigDb: 6, requiredSnrDb: 8, acrDb: 35, bdrDb: 60 },
        antenna: { type: "omni_dipole", gainDbi: 3, pattern: "omnidirectional", polarization: "vertical", heightM: 1.5, cableLossDb: 0.4, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 25, adaptiveDataRate: true },
      },
    },
  },

  "doodle-labs-mesh-rider": {
    label: "Doodle Labs Mesh Rider",
    programs: {
      "915-mesh": {
        label: "Mesh Rider 915 MHz",
        notes: "Approximate Doodle Labs Mesh Rider 915 MHz MANET profile for UAS and robotic backhaul.",
        rf: { frequencyMHz: 915, bandwidthKHz: 10000, modulation: "COFDM", waveform: "Mesh Rider", duplex: "full-duplex", channelSpacingKHz: 10000 },
        tx: { powerW: 1, dutyCycle: 1, papr: 8, spectralEfficiency: 2 },
        rx: { sensitivityDbm: -98, noiseFigDb: 6, requiredSnrDb: 8, acrDb: 35, bdrDb: 60 },
        antenna: { type: "omni_dipole", gainDbi: 2, pattern: "omnidirectional", polarization: "vertical", heightM: 1.5, cableLossDb: 0.3, systemLossDb: 1.5 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: true, relayCapable: true, maxHops: 10, latencyMs: 20, adaptiveDataRate: true, dataRateMbps: 20, meshProtocol: "Mesh Rider" },
      },
      "2450-mesh": {
        label: "Mesh Rider 2.45 GHz",
        notes: "Approximate Doodle Labs Mesh Rider 2.45 GHz MANET profile for higher-capacity UAS backhaul.",
        rf: { frequencyMHz: 2450, bandwidthKHz: 20000, modulation: "COFDM", waveform: "Mesh Rider", duplex: "full-duplex", channelSpacingKHz: 20000 },
        tx: { powerW: 1, dutyCycle: 1, papr: 8, spectralEfficiency: 4 },
        rx: { sensitivityDbm: -95, noiseFigDb: 6, requiredSnrDb: 8, acrDb: 35, bdrDb: 60 },
        antenna: { type: "omni_dipole", gainDbi: 3, pattern: "omnidirectional", polarization: "vertical", heightM: 1.5, cableLossDb: 0.3, systemLossDb: 1.5 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: true, relayCapable: true, maxHops: 10, latencyMs: 15, adaptiveDataRate: true, dataRateMbps: 60, meshProtocol: "Mesh Rider" },
      },
    },
  },

  "neros-archer": {
    label: "Neros Archer",
    programs: {
      "anti-jam-c2-placeholder": {
        label: "Anti-Jam C2 Placeholder",
        notes: "Approximate inferred placeholder for the Neros Archer control link pending public RF disclosure.",
        rf: { frequencyMHz: 2400, bandwidthKHz: 5000, modulation: "FHSS", waveform: "Archer Anti-Jam C2", duplex: "half-duplex", channelSpacingKHz: 5000 },
        tx: { powerW: 1, dutyCycle: 0.5, papr: 3, spectralEfficiency: 1.2 },
        rx: { sensitivityDbm: -100, noiseFigDb: 6, requiredSnrDb: 7, acrDb: 40, bdrDb: 65 },
        antenna: { type: "omni_dipole", gainDbi: 2, pattern: "omnidirectional", polarization: "vertical", heightM: 1.5, cableLossDb: 0.3, systemLossDb: 2 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 15, adaptiveDataRate: true },
      },
    },
  },

  "silvus-sc4200": {
    label: "Silvus StreamCaster 4200",
    programs: {
      "mimo-2x2": {
        label: "MIMO 2Ã—2 â€” 2.4 GHz",
        rf: { frequencyMHz: 2400, bandwidthKHz: 20000, modulation: "OFDM", waveform: "MIMO", duplex: "full-duplex", channelSpacingKHz: 20000 },
        tx: { powerW: 1, dutyCycle: 1, papr: 10, spectralEfficiency: 6 },
        rx: { sensitivityDbm: -95, noiseFigDb: 7, requiredSnrDb: 8, acrDb: 35, bdrDb: 60 },
        antenna: { type: "mimo_patch", gainDbi: 3, pattern: "omnidirectional", polarization: "dual", heightM: 1.5, cableLossDb: 0.3, systemLossDb: 1 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: true, relayCapable: true, maxHops: 10, latencyMs: 15, adaptiveDataRate: true, dataRateMbps: 60, meshProtocol: "MN-MIMO" },
      },
      "mimo-2x2-4900": {
        label: "MIMO 2Ã—2 â€” 4.9 GHz",
        rf: { frequencyMHz: 4940, bandwidthKHz: 20000, modulation: "OFDM", waveform: "MIMO", duplex: "full-duplex", channelSpacingKHz: 20000 },
        tx: { powerW: 1, dutyCycle: 1, papr: 10, spectralEfficiency: 6 },
        rx: { sensitivityDbm: -93, noiseFigDb: 7, requiredSnrDb: 8, acrDb: 35, bdrDb: 60 },
        antenna: { type: "mimo_patch", gainDbi: 5, pattern: "omnidirectional", polarization: "dual", heightM: 1.5, cableLossDb: 0.3, systemLossDb: 1 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: true, relayCapable: true, maxHops: 10, latencyMs: 15, adaptiveDataRate: true, dataRateMbps: 60, meshProtocol: "MN-MIMO" },
      },
    },
  },

  "silvus-sc4400": {
    label: "Silvus StreamCaster 4400",
    programs: {
      "mimo-4x4-2400": {
        label: "MIMO 4Ã—4 â€” 2.4 GHz (High-Cap)",
        rf: { frequencyMHz: 2400, bandwidthKHz: 40000, modulation: "OFDM", waveform: "MIMO", duplex: "full-duplex", channelSpacingKHz: 40000 },
        tx: { powerW: 2, dutyCycle: 1, papr: 10, spectralEfficiency: 8 },
        rx: { sensitivityDbm: -97, noiseFigDb: 6, requiredSnrDb: 8, acrDb: 38, bdrDb: 62 },
        antenna: { type: "mimo_array", gainDbi: 6, pattern: "omnidirectional", polarization: "dual", heightM: 2, cableLossDb: 0.3, systemLossDb: 1 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: true, relayCapable: true, maxHops: 12, latencyMs: 10, adaptiveDataRate: true, dataRateMbps: 120, meshProtocol: "MN-MIMO" },
      },
      "mimo-4x4-5800": {
        label: "MIMO 4Ã—4 â€” 5.8 GHz (High-Cap)",
        rf: { frequencyMHz: 5800, bandwidthKHz: 40000, modulation: "OFDM", waveform: "MIMO", duplex: "full-duplex", channelSpacingKHz: 40000 },
        tx: { powerW: 2, dutyCycle: 1, papr: 10, spectralEfficiency: 8 },
        rx: { sensitivityDbm: -95, noiseFigDb: 6, requiredSnrDb: 8, acrDb: 38, bdrDb: 62 },
        antenna: { type: "mimo_array", gainDbi: 8, pattern: "omnidirectional", polarization: "dual", heightM: 2, cableLossDb: 0.3, systemLossDb: 1 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: true, relayCapable: true, maxHops: 12, latencyMs: 10, adaptiveDataRate: true, dataRateMbps: 150, meshProtocol: "MN-MIMO" },
      },
      "mimo-4x4-4900": {
        label: "MIMO 4Ã—4 â€” 4.9 GHz (Public Safety)",
        rf: { frequencyMHz: 4940, bandwidthKHz: 40000, modulation: "OFDM", waveform: "MIMO", duplex: "full-duplex", channelSpacingKHz: 40000 },
        tx: { powerW: 2, dutyCycle: 1, papr: 10, spectralEfficiency: 8 },
        rx: { sensitivityDbm: -95, noiseFigDb: 6, requiredSnrDb: 8, acrDb: 38, bdrDb: 62 },
        antenna: { type: "mimo_array", gainDbi: 7, pattern: "omnidirectional", polarization: "dual", heightM: 2, cableLossDb: 0.3, systemLossDb: 1 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: true, relayCapable: true, maxHops: 12, latencyMs: 10, adaptiveDataRate: true, dataRateMbps: 130, meshProtocol: "MN-MIMO" },
      },
    },
  },

  "mpu-5": {
    label: "Persistent Systems Wave Relay MPU-5",
    programs: {
      "wave-relay-2400": {
        label: "Wave Relay MANET â€” 2.4 GHz",
        rf: { frequencyMHz: 2400, bandwidthKHz: 20000, modulation: "OFDM", waveform: "Wave Relay", duplex: "full-duplex", channelSpacingKHz: 20000 },
        tx: { powerW: 1, dutyCycle: 1, papr: 9, spectralEfficiency: 5 },
        rx: { sensitivityDbm: -96, noiseFigDb: 7, requiredSnrDb: 9, acrDb: 35, bdrDb: 60 },
        antenna: { type: "omni_dipole", gainDbi: 2, pattern: "omnidirectional", polarization: "vertical", heightM: 1.5, cableLossDb: 0.3, systemLossDb: 1.5 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: true, relayCapable: true, maxHops: 15, latencyMs: 12, adaptiveDataRate: true, dataRateMbps: 50, meshProtocol: "Wave Relay MANET" },
      },
      "wave-relay-4900": {
        label: "Wave Relay MANET â€” 4.9 GHz",
        rf: { frequencyMHz: 4940, bandwidthKHz: 20000, modulation: "OFDM", waveform: "Wave Relay", duplex: "full-duplex", channelSpacingKHz: 20000 },
        tx: { powerW: 1, dutyCycle: 1, papr: 9, spectralEfficiency: 5 },
        rx: { sensitivityDbm: -93, noiseFigDb: 7, requiredSnrDb: 9, acrDb: 35, bdrDb: 60 },
        antenna: { type: "omni_dipole", gainDbi: 3, pattern: "omnidirectional", polarization: "vertical", heightM: 1.5, cableLossDb: 0.3, systemLossDb: 1.5 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: true, relayCapable: true, maxHops: 15, latencyMs: 12, adaptiveDataRate: true, dataRateMbps: 55, meshProtocol: "Wave Relay MANET" },
      },
      "wave-relay-5800": {
        label: "Wave Relay MANET â€” 5.8 GHz",
        rf: { frequencyMHz: 5800, bandwidthKHz: 40000, modulation: "OFDM", waveform: "Wave Relay", duplex: "full-duplex", channelSpacingKHz: 40000 },
        tx: { powerW: 1, dutyCycle: 1, papr: 9, spectralEfficiency: 6 },
        rx: { sensitivityDbm: -94, noiseFigDb: 7, requiredSnrDb: 9, acrDb: 35, bdrDb: 60 },
        antenna: { type: "omni_dipole", gainDbi: 4, pattern: "omnidirectional", polarization: "vertical", heightM: 1.5, cableLossDb: 0.3, systemLossDb: 1.5 },
        prop: { model: "itu-p526", clutter: "open", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: true, relayCapable: true, maxHops: 15, latencyMs: 12, adaptiveDataRate: true, dataRateMbps: 80, meshProtocol: "Wave Relay MANET" },
      },
    },
  },

  "trellisware-tw950": {
    label: "TrellisWare TW-950",
    programs: {
      "tsm-x-manet": {
        label: "TSM-X MANET",
        rf: { frequencyMHz: 2400, bandwidthKHz: 5000, modulation: "OFDM", waveform: "TSM-X", duplex: "full-duplex", channelSpacingKHz: 5000 },
        tx: { powerW: 1, dutyCycle: 1, papr: 8, spectralEfficiency: 2.2 },
        rx: { sensitivityDbm: -97, noiseFigDb: 7, requiredSnrDb: 9, acrDb: 34, bdrDb: 62 },
        antenna: { type: "blade", gainDbi: 1, pattern: "omnidirectional", polarization: "vertical", heightM: 1.5, cableLossDb: 0.3, systemLossDb: 1.8 },
        prop: { model: "itu-p526", clutter: "urban", terrainEnabled: true, diffractionEnabled: true },
        net: { isManet: true, relayCapable: true, maxHops: 10, latencyMs: 20, adaptiveDataRate: true, dataRateMbps: 12, meshProtocol: "TSM-X" },
      },
    },
  },

  "starlink-military": {
    label: "Starlink / Starshield LEO SATCOM",
    programs: {
      "starlink-standard": {
        label: "Starlink Standard (Ku-band)",
        rf: { frequencyMHz: 13500, bandwidthKHz: 250000, modulation: "OFDM", waveform: "Link 182", duplex: "full-duplex", channelSpacingKHz: 250000 },
        tx: { powerW: 40, dutyCycle: 1, papr: 8, spectralEfficiency: 8 },
        rx: { sensitivityDbm: -90, noiseFigDb: 3, requiredSnrDb: 10, acrDb: 40, bdrDb: 60 },
        antenna: { type: "phased_array", gainDbi: 38, pattern: "steerable", polarization: "circular", heightM: 0.6, cableLossDb: 0.5, systemLossDb: 2 },
        prop: { model: "itu-p618", clutter: "open", terrainEnabled: false, diffractionEnabled: false },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 25, adaptiveDataRate: true, satcomEnabled: true, satType: "LEO", satUplinkMHz: 14000, satDownlinkMHz: 11200, satGainDbi: 38, dataRateMbps: 200 },
      },
      "starshield-ka": {
        label: "Starshield (Ka-band â€” Gov/Mil)",
        rf: { frequencyMHz: 29500, bandwidthKHz: 500000, modulation: "OFDM", waveform: "Link 182", duplex: "full-duplex", channelSpacingKHz: 500000 },
        tx: { powerW: 60, dutyCycle: 1, papr: 8, spectralEfficiency: 10 },
        rx: { sensitivityDbm: -88, noiseFigDb: 2.5, requiredSnrDb: 10, acrDb: 45, bdrDb: 65 },
        antenna: { type: "phased_array", gainDbi: 42, pattern: "steerable", polarization: "circular", heightM: 0.6, cableLossDb: 0.5, systemLossDb: 2 },
        prop: { model: "itu-p618", clutter: "open", terrainEnabled: false, diffractionEnabled: false },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 20, adaptiveDataRate: true, satcomEnabled: true, satType: "LEO", satUplinkMHz: 29500, satDownlinkMHz: 19700, satGainDbi: 42, dataRateMbps: 500, encrypted: true, milStandard: "Starshield" },
      },
    },
  },

  "prc-160-hf": {
    label: "AN/PRC-160 HF ALE Manpack",
    programs: {
      "hf-nvis-ale": {
        label: "HF NVIS â€” ALE 2â€“12 MHz",
        rf: { frequencyMHz: 7, bandwidthKHz: 3, modulation: "USB", waveform: "MIL-STD-188-141B ALE", duplex: "half-duplex", channelSpacingKHz: 3 },
        tx: { powerW: 20, dutyCycle: 0.5, papr: 0, spectralEfficiency: 0.4 },
        rx: { sensitivityDbm: -115, noiseFigDb: 10, requiredSnrDb: 6, acrDb: 60, bdrDb: 90 },
        antenna: { type: "whip_hf", gainDbi: 2, pattern: "omnidirectional", polarization: "vertical", heightM: 5.5, cableLossDb: 0.5, systemLossDb: 2 },
        prop: { model: "hf-skywave", clutter: "open", terrainEnabled: false, diffractionEnabled: false, nvisEnabled: true, ionoModel: "itu-r", timeDayEffects: true, solarIndex: 80 },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 500, adaptiveDataRate: false, hfDataRate: "2400bps", milStandard: "MIL-STD-188-141B" },
      },
      "hf-longhaul-ale": {
        label: "HF Long-Haul â€” 12â€“30 MHz",
        rf: { frequencyMHz: 18, bandwidthKHz: 3, modulation: "USB", waveform: "MIL-STD-188-141B ALE", duplex: "half-duplex", channelSpacingKHz: 3 },
        tx: { powerW: 20, dutyCycle: 0.5, papr: 0, spectralEfficiency: 0.4 },
        rx: { sensitivityDbm: -115, noiseFigDb: 10, requiredSnrDb: 6, acrDb: 60, bdrDb: 90 },
        antenna: { type: "dipole_hf", gainDbi: 2.15, pattern: "directional", polarization: "horizontal", heightM: 8, cableLossDb: 1, systemLossDb: 3 },
        prop: { model: "hf-skywave", clutter: "open", terrainEnabled: false, diffractionEnabled: false, nvisEnabled: false, ionoModel: "itu-r", timeDayEffects: true, solarIndex: 80 },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 800, adaptiveDataRate: false, hfDataRate: "2400bps", milStandard: "MIL-STD-188-141B" },
      },
      "hf-data-stanag": {
        label: "HF Data â€” STANAG 4538",
        rf: { frequencyMHz: 10, bandwidthKHz: 3, modulation: "PSK", waveform: "STANAG-4538", duplex: "half-duplex", channelSpacingKHz: 3 },
        tx: { powerW: 20, dutyCycle: 0.5, papr: 3, spectralEfficiency: 1.2 },
        rx: { sensitivityDbm: -115, noiseFigDb: 10, requiredSnrDb: 8, acrDb: 55, bdrDb: 85 },
        antenna: { type: "whip_hf", gainDbi: 2, pattern: "omnidirectional", polarization: "vertical", heightM: 5.5, cableLossDb: 0.5, systemLossDb: 2 },
        prop: { model: "hf-skywave", clutter: "open", terrainEnabled: false, diffractionEnabled: false, nvisEnabled: true, ionoModel: "itu-r", timeDayEffects: true, solarIndex: 80 },
        net: { isManet: false, relayCapable: false, maxHops: 1, latencyMs: 600, adaptiveDataRate: true, hfDataRate: "19200bps", milStandard: "STANAG-4538" },
      },
    },
  },

  ...RADAR_EMITTER_LIBRARY,
};


export { EMITTER_LIBRARY, RADAR_EMITTER_LIBRARY };

